name: "Wheres my review"
author: "Omid Mirzaee Yazdi"
branding:
  icon: 'phone-call'  
  color: 'red'

description: "Poke your senoir developer to review your code"

inputs:
  who:
    description: "Who to poke"
    required: false
    default: "Mr. so called senior developer!"
  number:
    description: "Phone number to call"
    required: true
  severity:
    description: "How angry do you want the poke to be?"
    required: false
    default: "outrageous"
  twilioSID:
    description: "Twilio account SID"
    required: true
  twilioAuthToken:
    description: "Twilio Auth token"
    required: true
  twilioNumber:
    description: "Twilio Number"
    required: true

outputs:
  time:
    description: "The time I poked them"
runs:
  using: "node16"
  main: "index.js"
